language: node_js

sudo: required
dist: trusty

env:
  global:
  - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache # includes bowers cache

install:
- cat /sys/fs/cgroup/memory/memory.limit_in_bytes
- cat /sys/fs/cgroup/memory/memory.soft_limit_in_bytes
- cat /proc/meminfo
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn --prefer-offline --pure-lockfile
- ./node_modules/bower/bin/bower install --config.interactive=false

script:
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
